# permissions for end users to edit p2codeschedulers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: p2code-scheduler
    app.kubernetes.io/managed-by: kustomize
  name: p2codescheduler-editor-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - p2codeschedulers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - p2codeschedulers/status
  verbs:
  - get
