# permissions for end users to view p2code-schedulers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: p2code-scheduler
    app.kubernetes.io/managed-by: kustomize
  name: p2code-scheduler-viewer-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - p2code-schedulers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - p2code-schedulers/status
  verbs:
  - get
