apiVersion: cache.example.com/v1alpha1
kind: P2codeScheduler
metadata:
  labels:
    app.kubernetes.io/name: p2code-scheduler
    app.kubernetes.io/managed-by: kustomize
  name: p2codescheduler-sample
spec:
  # TODO(user): Add fields here
